stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

debug-oidc:
  stage: .pre
  image: alpine:3.20
  id_tokens:
    OIDC_TOKEN:
      aud: https://gitlab.prolifel.com
  script:
    - echo -n "$OIDC_TOKEN" > oidc_token.txt
  artifacts:
    paths:
      - oidc_token.txt
    expire_in: 10 mins
