account_name: security
email: mencemaskan123+cloudsecurity@gmail.com
managed_org_unit: security
owner: security-team
environment: prod
cost_center: XACLOUDSEC
regions:
  - us-west-2
tags:
  Application: workload
  DataClassification: confidential
