server {
  set $forward_scheme http;
  set $server "gitlab";
  set $port 80;
  listen 80;
  server_name gitlab.example.com;

  location /.well-known/ {
    proxy_pass http://gitlab:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location /oauth/discovery/keys {
    proxy_pass http://gitlab:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location / { return 404; }
}
